apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.component }}
spec:
{{ if .Values.initContainers.enabled }}
  initContainers:
    - name: vault
      image: pavanidevops78/kubernetes:l1
      env:
        - name: VAULT_ADDR
          value: "https://100.29.15.98:8200/"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
              optional: true
        - name: SECRET_NAME
          value: common/{{ .Values.component }}
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
      volumeMounts:
        - mountPath: /data
          name: vault
  volumes:
  - name: vault
    emptyDir:
    sizeLimit: 5Mi
  {{ end }}
  containers:
   - name: {{ .Values.component }}
     image: pavanidevops78/kubernetes:v2
      {{ if .Values.initContainers.enabled }}
     volumeMounts:
      - mountPath: /data
        name: vault
         {{ end }}
